### ISSUE TITLE
HeroToast/ToastConfiguration.swift:5: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by 452MJ** [react-native-hero/toast#1]
iOS release包运行的时候报错

**Comment by musicode** [comment]
截图看下报错在哪一行

**Comment by 452MJ** [comment]
HeroToast/ToastConfiguration.swift:5 @musicode

**Comment by 452MJ** [comment]
本地debug包一切正常，release包就crash了

**Comment by musicode** [comment]
这个问题要等我有空再改，改好会在这说

**Comment by musicode** [comment]
想问下你的 release 包是改了什么配置，一般我自己打包就是 `Product` -> `Archive`，没发现报错

**Comment by 452MJ** [comment]
由于要做环境区分，我在`Projects`->`Targets`里面进行Duplicate(`cmd+D`)，来修改不同的环境配置（如Beta/Prod），再对Target Prod进行Archive

**Comment by musicode** [comment]
```
npx react-native init AwesomeProject --version 0.64.1
cd AwesomeProject
yarn add @react-native-hero/toast
cd ios
yarn install
```

打开 `AwesomeProject.xcworkspace`，Product -> Archive，没报错，如有报错，按这个流程告知步骤

**Comment by 452MJ** [comment]
新项目复现不了，先关了吧
